[package]
name = "proto-client"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic.workspace = true
prost.workspace = true
protos-commons.workspace = true

[build-dependencies]
tonic-build = { workspace = true }
