[package]
name = "eval-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn.workspace = true
darling.workspace = true
proc-macro2.workspace = true
quote.workspace = true
